/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.basic.demo;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App1 classUnderTest = new App1();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
