/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.basic.demo;

import org.testng.annotations.*;
import static org.testng.Assert.*;
import com.my.demo.App;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
